name: Python CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r services/requirements.txt

    - name: Start LocalStack
      uses: localstack/setup-localstack@v0.2.3
      with:
        image-tag: 'latest'
        install-awslocal: 'true'
      env:
        SERVICES: sqs,dynamodb
        DEFAULT_REGION: us-east-1

    - name: Wait for LocalStack to be ready
      run: |
        echo "Waiting for LocalStack to be ready..."
        sleep 10

    - name: Run tests with pytest
      run: |
        PYTHONPATH=. pytest tests
